<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Transcencode/Models.cs" Link="Models.cs" />
    <Compile Include="../../src/Transcencode/HandBrakeCommandBuilder.cs" Link="HandBrakeCommandBuilder.cs" />
    <Compile Include="../../src/Transcencode/HandBrakeCliService.cs" Link="HandBrakeCliService.cs" />
  </ItemGroup>
</Project>
